### ISSUE TITLE
HOW make the things align to the paragraph:？

### ISSUE THREAD

**Issue by eteled126** [peiche/recover#21]
I put a jwplayer video into the post, it always on the most left place；
I put a social shortcode into the post, it always on the most left place；
……
how can i align these element  to the left of the paragraph-text？or center？

The relevant page，part3：
http://wwweb.men/web/2131.html

**Comment by peiche** [comment]
This should be fixed in v1.1.2, which is live on wordpress.org now. Please update your theme and let me know.

**Comment by peiche** [comment]
Cover2 uses full-width elements, so that it works with [Aesop Story Engine](http://aesopstoryengine.com) and the [Gutenberg](https://wordpress.org/plugins/gutenberg/) plugins. As a result, any `<div>` elements not explicitly exempted will be full-width and left-aligned. You can get around with without modifying the theme CSS by wrapping elements with the following markup:

```
<div class="container">
  <!-- your content here -->
</div>
```

This will make a container whose width matches the paragraph tags. You can make a wider container (also not full-width) with this:

```
<div class="container large">
```

Alternatively, you can make a Cover2 child theme and add your CSS to its stylesheet.

**Comment by eteled126** [comment]
Thank you so much. your answer solved my problems!
nice!
